In [29]:
## ASSIGNMENT NUMPY 

In [ ]:
## question number 1

import numpy as np
x = np.zeros(10)
x[6] = 11
print(x)

In [12]:
## uestion number 2

import numpy as np
v = np.arange(10,50)
print(v)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
## question number 3

import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
## question number 4

import numpy as np
nums = np.array([1,2,0,0,4,0])
print(nums)
print("Indices of elements not equal to zero of the array:")
result = np.where(nums != 0)[0]
print(result)

[1 2 0 0 4 0]
Indices of elements not equal to zero of the array:
[0 1 4]


In [15]:
##question number 5

import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.65621268 0.20650877 0.1633411  0.50052604 0.66738272 0.40286498
  0.45128082 0.61952579 0.26360729 0.62213047]
 [0.44880213 0.09242951 0.0465404  0.96618976 0.91471543 0.27118663
  0.84235957 0.6196329  0.60335472 0.39299676]
 [0.27583222 0.66822285 0.35834737 0.01174247 0.69998193 0.55922624
  0.43589308 0.30679804 0.69971821 0.93521284]
 [0.88120516 0.42315988 0.46860093 0.38335793 0.80234553 0.97151088
  0.59333486 0.36517712 0.8470187  0.01627357]
 [0.35078647 0.93478613 0.15048682 0.84085512 0.58093267 0.66371274
  0.97876033 0.56678794 0.59095633 0.75293861]
 [0.25088989 0.4790779  0.23330403 0.70494808 0.03115846 0.55557237
  0.68458024 0.16229589 0.93818457 0.88304395]
 [0.21376078 0.40328388 0.62693416 0.19868978 0.35350735 0.55264483
  0.84823698 0.51486832 0.58167197 0.57435525]
 [0.96629405 0.95013592 0.93850679 0.66751387 0.59509677 0.98319097
  0.0328027  0.38479433 0.98250134 0.80830161]
 [0.53078144 0.03654255 0.49422337 0.42344527 0.62137607 0.74254

In [20]:
## question number 6

import numpy as np
x = np.random.random(30)
print(x)
print("mean of the random vector is")
m = x.mean()
print(m)



[0.62253498 0.68931631 0.72010829 0.84755219 0.29470583 0.89010501
 0.64409176 0.2275499  0.10569454 0.48213462 0.76883266 0.90710133
 0.23145663 0.38464955 0.82920825 0.30970771 0.34461108 0.693529
 0.29519354 0.2454031  0.17399713 0.07915247 0.2678695  0.1204523
 0.19184171 0.68879396 0.66482446 0.03820809 0.91201625 0.0125044 ]
mean of the random vector is
0.456104885460355
